version: '3.8'

services:
  # Container do seu Backend Python / FastAPI
  backend:
    build: .
    container_name: os_backend_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  # Container do Frontend do Alexandre usando Nginx
  frontend:
    build: ../os-frontend
    container_name: os_frontend_container
    ports:
      - "5600:80"
    depends_on:
      - backend