services:
  # ==========================================
  # 1. BANCO DE DADOS (POSTGRESQL 15)
  # ==========================================
  database:
    image: postgres:15
    container_name: sistema_os_database
    restart: always
    environment:
      POSTGRES_DB: sistema_os_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root_password_ufam_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gti_network

  # ==========================================
  # 2. BACKEND (FASTAPI + ASYNCPG)
  # ==========================================
  backend:
    build: ./os-backend
    container_name: sistema_os_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # String de conexão assíncrona usando as credenciais corretas do Postgres
      DATABASE_URL: "postgresql+asyncpg://postgres:root_password_ufam_2026@database:5432/sistema_os_db"
      
      # Segurança JWT (Mapeada do seu auth_routers.py)
      SECRET_KEY: "SUPER_SECRET_KEY_MIGRACAO_UFAM_ICET_2026_SECURITY"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 480
      
      # Mensageria SMTP Institucional
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 587
      SMTP_USER: "arnaldff@gmail.com"
      SMTP_PASSWORD: "lsjcpvgpmamlvjdb"
    depends_on:
      - database
    networks:
      - gti_network

  # ==========================================
  # 3. FRONTEND (REACTIVE INTERFACE)
  # ==========================================
  frontend:
    build: ./os-frontend
    container_name: sistema_os_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - gti_network

volumes:
  postgres_data:

networks:
  gti_network:
    driver: bridge